"""
dspy_optimizer.py — Оптимизация промптов (DSPy MIPROv2 + LLM fallback)
========================================================================
Два режима оптимизации:
  1. DSPy MIPROv2 — если dspy установлен и trainset >= 3
     - Trainset читается из ChromaDB (одобрённые промпты)
     - Compiled program кешируется на диске
  2. LLM-based fallback — прямой вызов LLM для улучшения промпта
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
from pathlib import Path
from typing import Any, Optional

from llm_router import LiteLLMClient
from state_types import ContextState

logger = logging.getLogger(__name__)

# Проверяем доступность DSPy
try:
    import dspy
    from dspy.teleprompt import MIPROv2

    _DSPY_AVAILABLE = True
    logger.info("✅ DSPy доступен — MIPROv2 будет использоваться для оптимизации.")
except ImportError:
    _DSPY_AVAILABLE = False
    logger.info("📝 DSPy не установлен — используем LLM-based оптимизацию.")


# =============================================================================
# DSPy Signature
# =============================================================================

if _DSPY_AVAILABLE:

    class PromptOptimizationSignature(dspy.Signature):
        """Optimize a prompt draft to maximize task fulfillment, factual accuracy, and minimize hallucination risk. Use few-shot examples as reference for quality bar."""

        original_request: str = dspy.InputField(
            desc="The original user request that the prompt must fulfill"
        )
        previous_draft: str = dspy.InputField(
            desc="The previous prompt draft that scored below threshold"
        )
        previous_score: float = dspy.InputField(
            desc="S_final score of the previous draft (0.0-1.0)"
        )
        weakness_hint: str = dspy.InputField(
            desc="What aspect scored lowest: task_fulfillment, rag_accuracy, or hallucination"
        )
        optimized_prompt: str = dspy.OutputField(
            desc="Improved prompt that addresses the weaknesses. Must be specific, structured, and hallucination-resistant."
        )


    class InstructionOptimizationSignature(dspy.Signature):
        """Improve an AI agent's system instructions based on past failure analysis to prevent similar issues in future iterations."""

        original_request: str = dspy.InputField(desc="The task the agent failed to fulfill perfectly")
        agent_role: str = dspy.InputField(desc="The role of the agent being optimized")
        failed_prompt: str = dspy.InputField(desc="The prompt draft generated by the agent")
        failure_analysis: str = dspy.InputField(desc="Technical analysis of why the prompt was suboptimal")
        current_instruction: str = dspy.InputField(desc="The agent's current system instruction")
        improved_instruction: str = dspy.OutputField(
            desc="Refined system instruction that incorporates the lessons learned. Keep it concise but more effective."
        )


# =============================================================================
# Metric function for MIPROv2
# =============================================================================

def prompt_quality_metric(example, prediction, trace=None) -> float:
    """
    Метрика качества оптимизированного промпта для MIPROv2.
    Оценивает: длину, наличие ключевых признаков, улучшение.
    """
    score = 0.0
    prompt_text = getattr(prediction, "optimized_prompt", "")

    if len(prompt_text) > 50:
        score += 0.3

    keywords = ["role", "task", "output", "format", "instruction", "step", "example"]
    if any(kw in prompt_text.lower() for kw in keywords):
        score += 0.4

    prev_score = getattr(example, "previous_score", 0.85)
    prev_draft = getattr(example, "previous_draft", "")
    if prev_score < 0.85 and len(prompt_text) > len(prev_draft):
        score += 0.3

    return min(1.0, score)


# =============================================================================
# Cold start synthetic trainset
# =============================================================================

_COLD_START_EXAMPLES = [
    {
        "original_request": "Создай промпт для анализа тональности текста",
        "previous_draft": "Анализируй текст",
        "previous_score": 0.4,
        "weakness_hint": "task_fulfillment",
        "optimized_prompt": (
            "You are a sentiment analysis expert. Analyze the following text and return a JSON with: "
            "{sentiment: positive|negative|neutral, confidence: 0.0-1.0, "
            "key_phrases: [list of phrases driving sentiment], "
            "summary: one sentence explanation}. Text: {input_text}"
        ),
    },
    {
        "original_request": "Промпт для генерации SQL запросов",
        "previous_draft": "Напиши SQL",
        "previous_score": 0.35,
        "weakness_hint": "rag_accuracy",
        "optimized_prompt": (
            "You are a senior SQL architect. Given the database schema: {schema} and "
            "user request: {request}, generate a valid SQL query. "
            "Rules: 1) Use only tables from the provided schema, "
            "2) Add comments explaining complex JOINs, "
            "3) Prefer CTEs over subqueries for readability. Return only the SQL code block."
        ),
    },
    {
        "original_request": "Создай музыкальный промпт через числа Фибоначчи",
        "previous_draft": "Используй Фибоначчи в музыке",
        "previous_score": 0.55,
        "weakness_hint": "hallucination",
        "optimized_prompt": (
            "You are a music theory expert specializing in mathematical patterns. "
            "Create a detailed composition guide using Fibonacci sequence (1,1,2,3,5,8,13,21). "
            "Specify: chord intervals mapped to sequence values, rhythmic patterns following the sequence, "
            "structural sections with Fibonacci-proportioned lengths. "
            "Ground all suggestions in established music theory. Avoid speculative claims."
        ),
    },
]


# =============================================================================
# LLM fallback prompt
# =============================================================================

_LLM_FALLBACK_PROMPT = """You are a prompt engineering expert. Previous prompt scored {previous_score:.2f}/1.0. Main weakness: {weakness_hint}. Original request: {original_request}. Previous draft: {previous_draft}. Write an improved prompt that specifically addresses the weakness. Be concrete, structured, include output format instructions. Return only the improved prompt text."""


# =============================================================================
# PromptOptimizer class
# =============================================================================

class PromptOptimizer:
    """
    Оптимизатор промптов:
      - DSPy MIPROv2 при наличии trainset >= 3
      - LLM fallback при trainset < 3 или ошибках DSPy
    """

    def __init__(
        self,
        llm_router: Optional[LiteLLMClient] = None,
        rag_manager: Any = None,
    ) -> None:
        self.router = llm_router or LiteLLMClient()
        self.rag_manager = rag_manager
        self._dspy_configured = False
        self._compiled_path = Path(
            os.getenv("DSPY_COMPILED_PROGRAM_PATH", "./dspy_compiled/optimizer.json")
        )
        self._last_trainset_size = 0

        # Инициализация DSPy LM если доступен
        if _DSPY_AVAILABLE and not self.router.is_mock:
            self._init_dspy()

    def _init_dspy(self) -> None:
        """Конфигурация DSPy LM — вызывается один раз в __init__."""
        try:
            dspy_model = os.getenv("DSPY_MODEL", "gpt-4o-mini")
            api_key = os.getenv("LLM_ROUTER_API_KEY", "")
            base_url = os.getenv("LLM_ROUTER_BASE_URL", "")

            lm_kwargs: dict[str, Any] = {
                "model": f"openai/{dspy_model}",
                "api_key": api_key,
            }
            if base_url:
                lm_kwargs["api_base"] = base_url

            lm = dspy.LM(**lm_kwargs)
            dspy.configure(lm=lm)
            self._dspy_configured = True
            logger.info("✅ DSPy сконфигурирован: model=openai/%s", dspy_model)

        except Exception as e:
            logger.warning("⚠️  Ошибка конфигурации DSPy: %s — используем LLM fallback", e)
            self._dspy_configured = False

    def _determine_weakness(self, state: ContextState) -> str:
        """Определить слабое место последнего черновика."""
        if not state.evaluation:
            return "general"

        scores = {
            "task_fulfillment": state.evaluation.task_fulfillment,
            "rag_accuracy": state.evaluation.rag_accuracy,
            "hallucination": 1.0 - state.evaluation.hallucination_penalty,
        }
        return min(scores, key=scores.get)  # type: ignore

    async def _build_trainset(self, state: ContextState) -> list:
        """
        Собрать trainset для MIPROv2:
        1. Из ChromaDB (одобрённые промпты) через rag_manager
        2. Если мало — добавить cold start synthetic примеры
        """
        trainset_examples = []

        # Из ChromaDB через rag_manager
        if self.rag_manager is not None:
            try:
                chromadb_results = await self.rag_manager.get_trainset_for_dspy(
                    query=state.request,
                    n=int(os.getenv("DSPY_OPTIMIZER_TRAINSET_SIZE", "5")),
                )
                for r in chromadb_results:
                    example = dspy.Example(
                        original_request=r["metadata"].get("original_request", ""),
                        previous_draft=str(r["text"]),
                        previous_score=float(r["metadata"].get("score", 0.85)),
                        weakness_hint="general",
                        optimized_prompt=str(r["text"]),
                    ).with_inputs(
                        "original_request",
                        "previous_draft",
                        "previous_score",
                        "weakness_hint",
                    )
                    trainset_examples.append(example)
            except Exception as e:
                logger.warning("⚠️  Не удалось получить trainset из ChromaDB: %s", e)

        # Если мало — добавить cold start примеры
        if len(trainset_examples) < 3:
            for item in _COLD_START_EXAMPLES:
                example = dspy.Example(
                    original_request=item["original_request"],
                    previous_draft=item["previous_draft"],
                    previous_score=item["previous_score"],
                    weakness_hint=item["weakness_hint"],
                    optimized_prompt=item["optimized_prompt"],
                ).with_inputs(
                    "original_request",
                    "previous_draft",
                    "previous_score",
                    "weakness_hint",
                )
                trainset_examples.append(example)

            logger.info("🧊 [DSPy] cold start synthetic trainset — %d примеров", len(trainset_examples))

        return trainset_examples

    async def _load_or_compile_program(self, trainset: list):
        """
        Загрузить compiled program или скомпилировать заново через MIPROv2.
        MIPROv2.compile() — синхронный, запускаем через asyncio.to_thread().
        """
        student = dspy.Predict(PromptOptimizationSignature)

        # Проверяем кеш
        if self._compiled_path.exists():
            # Если trainset не вырос > 50% — используем кеш
            if (
                self._last_trainset_size > 0
                and len(trainset) <= self._last_trainset_size * 1.5
            ):
                try:
                    student.load(str(self._compiled_path))
                    logger.info("📂 [DSPy] Загружена скомпилированная программа из %s", self._compiled_path)
                    return student
                except Exception as e:
                    logger.warning("⚠️  Не удалось загрузить compiled program: %s", e)

        # Компиляция через MIPROv2
        logger.info(
            "⏳ [DSPy] Компиляция MIPROv2 (trainset=%d, auto='light'). "
            "Это может занять 30-90 секунд и ~10-20 LLM-вызовов...",
            len(trainset),
        )

        max_bootstrapped = int(os.getenv("DSPY_MAX_BOOTSTRAPPED_DEMOS", "3"))
        max_labeled = int(os.getenv("DSPY_MAX_LABELED_DEMOS", "2"))
        timeout_seconds = float(os.getenv("DSPY_TIMEOUT_SECONDS", "120"))

        def _compile():
            optimizer = MIPROv2(
                metric=prompt_quality_metric,
                auto="light",
                num_threads=1,
            )
            compiled = optimizer.compile(
                student=student,
                trainset=trainset,
                max_bootstrapped_demos=max_bootstrapped,
                max_labeled_demos=max_labeled,
            )
            return compiled

        try:
            compiled_program = await asyncio.wait_for(
                asyncio.to_thread(_compile),
                timeout=timeout_seconds,
            )

            # Сохраняем на диск
            self._compiled_path.parent.mkdir(parents=True, exist_ok=True)
            compiled_program.save(str(self._compiled_path))
            self._last_trainset_size = len(trainset)

            logger.info("✅ [DSPy] MIPROv2 скомпилирован и сохранён в %s", self._compiled_path)
            return compiled_program

        except asyncio.TimeoutError:
            logger.warning("⏱️  [DSPy] MIPROv2 compile timeout (%ds) — используем LLM fallback", timeout_seconds)
            raise
        except Exception as e:
            logger.warning("⚠️  [DSPy] MIPROv2 compile error: %s — используем LLM fallback", e)
            raise

    async def optimize(self, state: ContextState) -> str:
        """Core optimization logic."""
        request = state.request
        last_entry = state.prompt_chain[-1] if state.prompt_chain else {}
        draft = last_entry.get("generated_text", "")
        score = state.current_score
        weakness = self._determine_weakness(state)

        if self._dspy_configured and _DSPY_AVAILABLE:
            try:
                trainset = await self._build_trainset(state)
                student = await self._load_or_compile_program(trainset)
                
                result = await asyncio.to_thread(
                    student,
                    original_request=request[:300],
                    previous_draft=draft[:1000],
                    previous_score=score,
                    weakness_hint=weakness
                )
                return getattr(result, "optimized_prompt", draft)
            except Exception as e:
                logger.warning("⚠️ DSPy Opt Error: %s — fallback to LLM", e)

        return await self._llm_optimize(
            request=request, 
            draft=draft, 
            score=score, 
            weakness_hint=weakness
        )

    async def optimize_prompt(self, state: ContextState, agents: dict = None) -> ContextState:
        """
        V2: Комплексная оптимизация.
        1. Улучшает текст текущего промпта (как раньше).
        2. Если score низкий (< 0.7) — анализирует причину и обновляет системную инструкцию агента.
        """
        current_draft = ""
        agent_id = ""
        if state.prompt_chain:
            last_entry = state.prompt_chain[-1]
            current_draft = last_entry.get("generated_text", "")
            agent_id = last_entry.get("agent_id", "")

        score = state.current_score
        weakness_hint = self._determine_weakness(state)
        
        # 1. Оптимизация текста промпта (через DSPy или Fallback)
        optimized_text = await self.optimize(state)
        state.optimized_prompt = optimized_text

        # 2. Самосовершенствование: Обновление инструкции агента если он 'виноват' в низком скоре
        if score < 0.7 and agents and agent_id in agents:
            agent = agents[agent_id]
            analysis = self._analyze_failure(state, weakness_hint)
            
            logger.info("🧠 [Optimizer] Попытка улучшить инструкцию агента %s...", agent_id)
            
            try:
                new_instr = await self._generate_improved_instruction(
                    request=state.request,
                    agent=agent,
                    failed_draft=current_draft,
                    analysis=analysis
                )
                if new_instr:
                    await agent.update_instruction(
                        new_instr, 
                        reason=f"Low score ({score:.2f}) on task fulfillment. Analysis: {analysis[:100]}..."
                    )
            except Exception as e:
                logger.warning("⚠️  Не удалось обновить инструкцию агента: %s", e)

        # Добавляем в цепочку
        state.prompt_chain.append({
            "agent_id": "optimizer",
            "agent_role": "Prompt Optimizer",
            "generated_text": optimized_text,
            "model_used": "dspy_mipro" if self._dspy_configured else "llm_fallback",
            "task_type": "medium",
            "latency_ms": 0,
            "metadata": {"iteration": state.iteration, "prev_score": score},
        })

        return state

    def _analyze_failure(self, state: ContextState, weakness: str) -> str:
        """Технический анализ провала для DSPy."""
        eval_data = state.evaluation
        if not eval_data:
            return "General quality issue."
        
        analysis = f"Score: {state.current_score:.2f}. "
        if weakness == "task_fulfillment":
            analysis += (f"Failed to fulfill user requirements. "
                         f"Missing parts: {[k for k,v in eval_data.task_fulfillment_breakdown.items() if v < 0.7]}")
        elif weakness == "rag_accuracy":
            analysis += "Failed to use provided context correctly or contradicted it."
        elif weakness == "hallucination":
            analysis += f"Hallucination detected (penalty {eval_data.hallucination_penalty})."
        
        return analysis

    async def _generate_improved_instruction(
        self, request: str, agent: Any, failed_draft: str, analysis: str
    ) -> str:
        """Генерация новой системной инструкции через DSPy или LLM."""
        
        if self._dspy_configured and _DSPY_AVAILABLE:
            try:
                # В будущем тут можно сделать полноценную DSPy программу для инструкций
                # Сейчас используем простой Predict
                predictor = dspy.Predict(InstructionOptimizationSignature)
                result = await asyncio.to_thread(
                    predictor,
                    original_request=request[:300],
                    agent_role=agent.agent_role,
                    failed_prompt=failed_draft[:500],
                    failure_analysis=analysis,
                    current_instruction=agent.system_instruction
                )
                return getattr(result, "improved_instruction", "")
            except Exception as e:
                logger.warning("⚠️ DSPy Instruction Opt Error: %s", e)

        # Fallback LLM
        messages = [
            {"role": "system", "content": "You are a Meta-Prompt Engineer. Your job is to fix AN AGENT'S SYSTEM INSTRUCTIONS so it stops making mistakes."},
            {"role": "user", "content": (
                f"Agent Role: {agent.agent_role}\n"
                f"Previous Task: {request[:200]}\n"
                f"Agent produced: {failed_draft[:300]}\n"
                f"Failure Analysis: {analysis}\n"
                f"Current System Instruction:\n{agent.system_instruction}\n\n"
                "PROPOSE AN IMPROVED SYSTEM INSTRUCTION for this agent. Keep it focused and impactful."
            )}
        ]
        
        resp = await self.router.generate(messages=messages, task_type="architect")
        return resp["content"]

    async def _llm_optimize(
        self,
        request: str,
        draft: str,
        score: float,
        weakness_hint: str,
    ) -> str:
        """Оптимизация через прямой LLM-вызов (fallback)."""
        prompt = _LLM_FALLBACK_PROMPT.format(
            original_request=request[:500],
            previous_draft=draft[:1500],
            previous_score=score,
            weakness_hint=weakness_hint,
        )

        messages = [
            {
                "role": "system",
                "content": (
                    "You are a prompt optimization expert. Return only the improved "
                    "prompt text without any preamble or explanation."
                ),
            },
            {"role": "user", "content": prompt},
        ]

        response = await self.router.generate(
            messages=messages,
            temperature=0.3,
            task_type="medium",
        )

        return response["content"]
